import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/Nav/NavBar";

export const metadata: Metadata = {
  title: "당근 편리해요",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
