import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/Nav/NavBar";
import getCurrentUser from "./\baction/getCurrentUser";

export const metadata: Metadata = {
  title: "당근 편리해요",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body>
        <NavBar currentUser={currentUser} />
        {children}
      </body>
    </html>
  );
}
